import type { Location, Food } from "@/types"

export const locations: Location[] = [
  {
    id: "1",
    name: "東京",
    nameEn: "Tokyo",
    slug: "tokyo",
    region: "関東",
    latitude: 35.6762,
    longitude: 139.6503,
    emoji: "🗼",
  },
  {
    id: "2",
    name: "大阪",
    nameEn: "Osaka",
    slug: "osaka",
    region: "関西",
    latitude: 34.6937,
    longitude: 135.5023,
    emoji: "🏯",
  },
  {
    id: "3",
    name: "京都",
    nameEn: "Kyoto",
    slug: "kyoto",
    region: "関西",
    latitude: 35.0116,
    longitude: 135.7681,
    emoji: "⛩️",
  },
  {
    id: "4",
    name: "福岡",
    nameEn: "Fukuoka",
    slug: "fukuoka",
    region: "九州",
    latitude: 33.5904,
    longitude: 130.4017,
    emoji: "🍜",
  },
  {
    id: "5",
    name: "札幌",
    nameEn: "Sapporo",
    slug: "sapporo",
    region: "北海道",
    latitude: 43.0642,
    longitude: 141.3469,
    emoji: "❄️",
  },
  {
    id: "6",
    name: "名古屋",
    nameEn: "Nagoya",
    slug: "nagoya",
    region: "中部",
    latitude: 35.1815,
    longitude: 136.9066,
    emoji: "🏮",
  },
  {
    id: "7",
    name: "奈良",
    nameEn: "Nara",
    slug: "nara",
    region: "関西",
    latitude: 34.6851,
    longitude: 135.8048,
    emoji: "🦌",
  },
  {
    id: "8",
    name: "広島",
    nameEn: "Hiroshima",
    slug: "hiroshima",
    region: "中国",
    latitude: 34.3853,
    longitude: 132.4553,
    emoji: "🌸",
  },
]

export const mockFoods: Record<string, Food[]> = {
  tokyo: [
    {
      id: "1",
      name: "東京ラーメン",
      nameEn: "Tokyo Ramen",
      description:
        "醤油ベースの透明なスープに細麺を合わせた、東京を代表するソウルフード。あっさりとした味わいが特徴で、チャーシュー、メンマ、ネギがトッピングされる。",
      shortDesc: "醤油ベースの透明スープ、東京のソウルフード",
      imageUrl: "/placeholder.svg?height=160&width=160",
      ranking: 1,
      priceRange: "¥800-1,200",
      priceRangeUsd: "$5-8",
      howToEat: "麺をすすって食べるのがマナー。音を立てても問題ありません。",
      culturalContext: "江戸時代から続く東京の伝統的な味。忙しい江戸っ子のファストフードとして発展。",
      locationId: "1",
      restaurants: [
        {
          id: "1",
          name: "一蘭 渋谷店",
          nameEn: "Ichiran Shibuya",
          address: "東京都渋谷区道玄坂2-29-11",
          googleMapUrl: "https://maps.google.com/?q=一蘭+渋谷店",
          features: ["英語メニュー", "24時間営業", "個室ブース"],
        },
      ],
      orderPhrases: [
        {
          id: "1",
          japanese: "ラーメンひとつください",
          romaji: "Ramen hitotsu kudasai",
          english: "One ramen please",
        },
      ],
    },
    {
      id: "2",
      name: "江戸前寿司",
      nameEn: "Edomae Sushi",
      description:
        "東京湾で獲れた新鮮な魚介を使用した伝統的な寿司。職人が目の前で握る本格的な江戸前スタイルで、シャリとネタの絶妙なバランスが楽しめる。",
      shortDesc: "東京湾の新鮮な魚介、伝統の江戸前スタイル",
      imageUrl: "/placeholder.svg?height=160&width=160",
      ranking: 2,
      priceRange: "¥3,000-8,000",
      priceRangeUsd: "$20-55",
      howToEat: "手で食べても箸で食べても構いません。醤油は少量つけて。",
      culturalContext: "江戸時代に屋台で始まった庶民の食べ物が、今や世界に誇る日本料理に。",
      locationId: "1",
      restaurants: [
        {
          id: "2",
          name: "築地 寿司大",
          nameEn: "Tsukiji Sushi Dai",
          address: "東京都中央区築地5-2-1",
          googleMapUrl: "https://maps.google.com/?q=築地+寿司大",
          features: ["新鮮な魚", "伝統的", "早朝営業"],
        },
      ],
      orderPhrases: [
        {
          id: "2",
          japanese: "おまかせでお願いします",
          romaji: "Omakase de onegaishimasu",
          english: "Chef's choice please",
        },
      ],
    },
    {
      id: "3",
      name: "もんじゃ焼き",
      nameEn: "Monjayaki",
      description:
        "東京下町発祥の鉄板料理。小麦粉を水で溶いた生地に具材を混ぜ、鉄板で焼きながら食べる。お好み焼きよりも水分が多く、独特の食感が楽しめる。",
      shortDesc: "東京下町発祥、鉄板で焼きながら食べる",
      imageUrl: "/placeholder.svg?height=160&width=160",
      ranking: 3,
      priceRange: "¥1,000-2,000",
      priceRangeUsd: "$7-14",
      howToEat: "小さなヘラで少しずつすくって食べます。みんなでシェアするのが一般的。",
      culturalContext: "月島が発祥の地。昭和の下町文化を代表する庶民の味。",
      locationId: "1",
      restaurants: [
        {
          id: "3",
          name: "だるま 月島本店",
          nameEn: "Daruma Tsukishima Honten",
          address: "東京都中央区月島1-7-4",
          googleMapUrl: "https://maps.google.com/?q=だるま+月島本店",
          features: ["体験型調理", "地元の雰囲気", "グループ向け"],
        },
      ],
      orderPhrases: [
        {
          id: "3",
          japanese: "もんじゃ焼きお願いします",
          romaji: "Monjayaki onegaishimasu",
          english: "Monjayaki please",
        },
      ],
    },
    {
      id: "4",
      name: "天ぷら",
      nameEn: "Tempura",
      description:
        "新鮮な海老や野菜を軽い衣で揚げた日本料理の代表格。サクサクの食感と素材の旨味を活かした上品な味わいが特徴。天つゆや塩で食べる。",
      shortDesc: "軽い衣でサクサク、海老と野菜の上品な味",
      imageUrl: "/placeholder.svg?height=160&width=160",
      ranking: 4,
      priceRange: "¥2,000-5,000",
      priceRangeUsd: "$14-35",
      howToEat: "天つゆにつけるか、塩で食べます。熱いうちに食べるのがポイント。",
      culturalContext: "江戸時代にポルトガルから伝来した調理法が日本独自に発展。",
      locationId: "1",
      restaurants: [
        {
          id: "4",
          name: "大黒家 浅草本店",
          nameEn: "Daikokuya Asakusa Honten",
          address: "東京都台東区浅草1-38-10",
          googleMapUrl: "https://maps.google.com/?q=大黒家+浅草本店",
          features: ["老舗", "伝統的調理法", "観光地"],
        },
      ],
      orderPhrases: [
        {
          id: "4",
          japanese: "天ぷら定食お願いします",
          romaji: "Tempura teishoku onegaishimasu",
          english: "Tempura set meal please",
        },
      ],
    },
    {
      id: "5",
      name: "うなぎ",
      nameEn: "Unagi",
      description:
        "蒲焼きにしたうなぎをご飯の上に乗せた丼料理。甘辛いタレが絡んだうなぎは栄養価が高く、夏バテ防止の効果があるとされる。",
      shortDesc: "甘辛タレの蒲焼き、栄養満点の丼料理",
      imageUrl: "/placeholder.svg?height=160&width=160",
      ranking: 5,
      priceRange: "¥2,500-4,000",
      priceRangeUsd: "$17-28",
      howToEat: "ご飯と一緒に食べます。山椒をかけると風味が増します。",
      culturalContext: "土用の丑の日に食べる習慣があり、江戸時代から続く伝統。",
      locationId: "1",
      restaurants: [
        {
          id: "5",
          name: "野田岩 麻布飯倉本店",
          nameEn: "Nodaiwa Azabu Iikura Honten",
          address: "東京都港区東麻布1-5-4",
          googleMapUrl: "https://maps.google.com/?q=野田岩+麻布飯倉本店",
          features: ["老舗", "高級", "伝統の味"],
        },
      ],
      orderPhrases: [
        {
          id: "5",
          japanese: "うな重お願いします",
          romaji: "Unaju onegaishimasu",
          english: "Grilled eel rice bowl please",
        },
      ],
    },
  ],
}
